# Generated by Django 5.0.3 on 2024-05-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdf_id_carrera'),
        ('core', '0010_rename_fundamenttacion_pdf_fundamentacion'),
    ]

    operations = [
    ]
