# Generated by Django 5.0.3 on 2024-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20240521_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='carga_Horaria_Semanal',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='carga_Horaria_Semestral',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='profesor',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='condicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='semestre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
